######################################################################
# Automatically generated by qmake (3.0) Sun Dec 13 21:44:00 2015
######################################################################

QT+=opengl
CONFIG+=c++11
LIBS+=-lGLU
TEMPLATE = app
TARGET = rendering
INCLUDEPATH += .

# Input
HEADERS += GLPolygonWidget.h Matrix.h Point.h Vector.h
SOURCES += GLPolygonMain.cpp GLPolygonWidget.cpp Matrix.cpp Point.cpp Vector.cpp
